### ISSUE TITLE
Post Mutation: Submission

### ISSUE THREAD

**Issue by AmoDinho** [AmoDinho/formulaone-graphql-client#1]
After trying to Create a new driver this is the error message: 

```
GraphQLError: Variable "$name" of required type "String!" was not provided.
    at getVariableValues (C:\Users\Sindile Xulu\Documents\GitHub\formulaone-graphql\server\node_modules\graphql\execution\values.js:69:23)    at buildExecutionContext (C:\Users\Sindile Xulu\Documents\GitHub\formulaone-graphql\server\node_modules\graphql\execution\execute.js:246:63)
    at executeImpl (C:\Users\Sindile Xulu\Documents\GitHub\formulaone-graphql\server\node_modules\graphql\execution\execute.js:140:17)
    at Object.execute (C:\Users\Sindile Xulu\Documents\GitHub\formulaone-graphql\server\node_modules\graphql\execution\execute.js:131:229)    at doRunQuery (C:\Users\Sindile Xulu\Documents\GitHub\formulaone-graphql\server\node_modules\apollo-server-core\dist\runQuery.js:124:42)
    at C:\Users\Sindile Xulu\Documents\GitHub\formulaone-graphql\server\node_modules\apollo-server-core\dist\runQuery.js:21:56
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
GraphQLError: Variable "$team" of required type "String!" was not provided.
    at getVariableValues (C:\Users\Sindile Xulu\Documents\GitHub\formulaone-graphql\server\node_modules\graphql\execution\values.js:69:23)    at buildExecutionContext (C:\Users\Sindile Xulu\Documents\GitHub\formulaone-graphql\server\node_modules\graphql\execution\execute.js:246:63)
    at executeImpl (C:\Users\Sindile Xulu\Documents\GitHub\formulaone-graphql\server\node_modules\graphql\execution\execute.js:140:17)
    at Object.execute (C:\Users\Sindile Xulu\Documents\GitHub\formulaone-graphql\server\node_modules\graphql\execution\execute.js:131:229)    at doRunQuery (C:\Users\Sindile Xulu\Documents\GitHub\formulaone-graphql\server\node_modules\apollo-server-core\dist\runQuery.js:124:42)
    at C:\Users\Sindile Xulu\Documents\GitHub\formulaone-graphql\server\node_modules\apollo-server-core\dist\runQuery.js:21:56
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
GraphQLError: Variable "$points" of required type "Int!" was not provided.
    at getVariableValues (C:\Users\Sindile Xulu\Documents\GitHub\formulaone-graphql\server\node_modules\graphql\execution\values.js:69:23)    at buildExecutionContext (C:\Users\Sindile Xulu\Documents\GitHub\formulaone-graphql\server\node_modules\graphql\execution\execute.js:246:63)
    at executeImpl (C:\Users\Sindile Xulu\Documents\GitHub\formulaone-graphql\server\node_modules\graphql\execution\execute.js:140:17)
    at Object.execute (C:\Users\Sindile Xulu\Documents\GitHub\formulaone-graphql\server\node_modules\graphql\execution\execute.js:131:229)    at doRunQuery (C:\Users\Sindile Xulu\Documents\GitHub\formulaone-graphql\server\node_modules\apollo-server-core\dist\runQuery.js:124:42)
    at C:\Users\Sindile Xulu\Documents\GitHub\formulaone-graphql\server\node_modules\apollo-server-core\dist\runQuery.js:21:56
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
GraphQLError: Variable "$pictureURL" of required type "String!" was not provided.
    at getVariableValues (C:\Users\Sindile Xulu\Documents\GitHub\formulaone-graphql\server\node_modules\graphql\execution\values.js:69:23)    at buildExecutionContext (C:\Users\Sindile Xulu\Documents\GitHub\formulaone-graphql\server\node_modules\graphql\execution\execute.js:246:63)
    at executeImpl (C:\Users\Sindile Xulu\Documents\GitHub\formulaone-graphql\server\node_modules\graphql\execution\execute.js:140:17)
    at Object.execute (C:\Users\Sindile Xulu\Documents\GitHub\formulaone-graphql\server\node_modules\graphql\execution\execute.js:131:229)    at doRunQuery (C:\Users\Sindile Xulu\Documents\GitHub\formulaone-graphql\server\node_modules\apollo-server-core\dist\runQuery.js:124:42)
    at C:\Users\Sindile Xulu\Documents\GitHub\formulaone-graphql\server\node_modules\apollo-server-core\dist\runQuery.js:21:56
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
GraphQLError: Variable "$country" of required type "String!" was not
provided.
    at getVariableValues (C:\Users\Sindile Xulu\Documents\GitHub\formulaone-graphql\server\node_modules\graphql\execution\values.js:69:23)    at buildExecutionContext (C:\Users\Sindile Xulu\Documents\GitHub\formulaone-graphql\server\node_modules\graphql\execution\execute.js:246:63)
    at executeImpl (C:\Users\Sindile Xulu\Documents\GitHub\formulaone-graphql\server\node_modules\graphql\execution\execute.js:140:17)
    at Object.execute (C:\Users\Sindile Xulu\Documents\GitHub\formulaone-graphql\server\node_modules\graphql\execution\execute.js:131:229)    at doRunQuery (C:\Users\Sindile Xulu\Documents\GitHub\formulaone-graphql\server\node_modules\apollo-server-core\dist\runQuery.js:124:42)
    at C:\Users\Sindile Xulu\Documents\GitHub\formulaone-graphql\server\node_modules\apollo-server-core\dist\runQuery.js:21:56
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
GraphQLError: Variable "$podiums" of required type "Int!" was not provided.
    at getVariableValues (C:\Users\Sindile Xulu\Documents\GitHub\formulaone-graphql\server\node_modules\graphql\execution\values.js:69:23)    at buildExecutionContext (C:\Users\Sindile Xulu\Documents\GitHub\formulaone-graphql\server\node_modules\graphql\execution\execute.js:246:63)
    at executeImpl (C:\Users\Sindile Xulu\Documents\GitHub\formulaone-graphql\server\node_modules\graphql\execution\execute.js:140:17)
    at Object.execute (C:\Users\Sindile Xulu\Documents\GitHub\formulaone-graphql\server\node_modules\graphql\execution\execute.js:131:229)    at doRunQuery (C:\Users\Sindile Xulu\Documents\GitHub\formulaone-graphql\server\node_modules\apollo-server-core\dist\runQuery.js:124:42)
    at C:\Users\Sindile Xulu\Documents\GitHub\formulaone-graphql\server\node_modules\apollo-server-core\dist\runQuery.js:21:56
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
GraphQLError: Variable "$championshipWins" of required type "Int!" was not provided.
    at getVariableValues (C:\Users\Sindile Xulu\Documents\GitHub\formulaone-graphql\server\node_modules\graphql\execution\values.js:69:23)    at buildExecutionContext (C:\Users\Sindile Xulu\Documents\GitHub\formulaone-graphql\server\node_modules\graphql\execution\execute.js:246:63)
    at executeImpl (C:\Users\Sindile Xulu\Documents\GitHub\formulaone-graphql\server\node_modules\graphql\execution\execute.js:140:17)
    at Object.execute (C:\Users\Sindile Xulu\Documents\GitHub\formulaone-graphql\server\node_modules\graphql\execution\execute.js:131:229)    at doRunQuery (C:\Users\Sindile Xulu\Documents\GitHub\formulaone-graphql\server\node_modules\apollo-server-core\dist\runQuery.js:124:42)
    at C:\Users\Sindile Xulu\Documents\GitHub\formulaone-graphql\server\node_modules\apollo-server-core\dist\runQuery.js:21:56
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

```

**Comment by AmoDinho** [comment]
This was not working because I was not authenticated.
